config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/contact' => 'static_pages#contact'

  get '/signup' => 'users#new'

  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  resources :users

  resources :microposts, only:[:create,:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :user_id , presence:true
  validates :content,presence:true,length:{maximum:140}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy

  before_save {self.email = email.downcase}
  validates :name, presence:true ,length: {maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence:true ,length: {maximum:255},
      format:{with: VALID_EMAIL_REGEX},
      uniqueness:{case_sensitive:false}

  has_secure_password
  validates :password, presence:true,length:{minimum:6}

  def feed
    Micropost.where("user_id=?", id)
  end


  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
   BCrypt::Password.create(string, cost: cost)
 end

 def User.new_token
   SecureRandom. urlsafe_base64
 end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


private
  def logged_in_user
    unless logged_in?
    store_location
    flash[:denger]="ログインして下さい"
    redirect_to login_url
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy]
before_action :correct_user, only:[:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:succes] = "投稿を保存しました"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end


  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
        else
    flash.now[:danger] ="Invalid email/password combination"
    render 'new'
    end
  end

  def destroy
      log_out
      redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items =  current_user.feed.paginate(page:params[:page])
    end
  end
  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit,:update,:index,:destroy]
  before_action :correct_user, only:[:edit,:update]
  before_action :admin_user, only: :destroy


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url
  end


  def index
    @users = User.paginate(page: params[:page])
  end


  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] =  "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    flash[:success] = "プロフィールを更新しました"
    redirect_to @user
    else
      render 'edit'
    end
  end
  private

    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end



    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwading_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size:50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.name,class:"gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#"></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "このアプリについて",   about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to("App",root_path,id:"logo")%>
      <nav>
        <ul class ="nav navbar-nav navbar-right">
          <li><%= link_to "ホーム",root_path%></li>
          <li><%= link_to "ヘルプ",help_path%></li>

          <% if logged_in? %>
            <li><%= link_to "ユーザー一覧", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               アカウント <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
             <li><%= link_to "設定", edit_user_path(current_user) %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "ログアウト", logout_path, method: :delete %>
             </li>
           </ul>
         </li>
       <%else%>
          <li><%= link_to "ログイン", login_path%></li>
        <%end%>
        </ul>
      </nav>
    </div>

</header>

app/views/layouts/_microposts.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

<%= will_paginate @microposts %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
  | <%= link_to "delete", user, method: :delete,
                               data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> | Ruby on Rails Tutorial Sample App</title>
    <%= render 'layouts/head'%>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message|%>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
    <%= link_to "削除", micropost, method: :delete,
                                     data: { confirm: "投稿を削除しますか？" } %>
  <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items%>
<%end%>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "投稿してみよう！" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "マイプロフィール", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>

<DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | Rails App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      このアプリケーションは学習用に作成しました。
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title,'Contact')%>
<h1>お問い合わせ</h1>
<P>
  こちらまでお願い致します。<br>n4gzp44bz_1@yahoo.co.jp
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>

<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title)%> | Rails App</title>
  </head>
  <body>
    <h1>ヘルプ</h1>
    <p>

    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title)%> |　Rails app</title>
  </head>
  <body>
    <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
          <h3>フィード</h3>
          <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
    <div class="center jumbotron">
      <h1 class = "msg">Rails app</h1>
      <h2>

      </h2>

      <%= link_to "新規登録はこちら！", signup_path , class: "btn btn-lg btn-primary" %>
    </div>


  <% end %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
  | <%= link_to "delete", user, method: :delete,
                               data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:button_text,'更新') %>

<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">画像変更</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー一覧</h1>



<ul class="users">
  <% @users.each do |user|%>
    <%= render user %>
    <%end%>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title,'Sign up!')%>
<%= provide(:button_text,'sign up!')%>
<h1>サインアップ</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form"%>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
      </h1>
    </section>
  </aside>

  <div class="col-md-8">
  <% if @user.microposts.any? %>
    <h3>件の投稿 (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
  <% end %>
  </div>
</div>